### ISSUE TITLE
Thrusters only connect 50% of the time

### ISSUE THREAD

**Issue by ShatteredPixelz** [JHSRobo/ROSbasic#125]

**Comment by ajgrinds** [comment]
IDK this is fixed now... 🤷

**Comment by Michael-Equi** [comment]
This is not fixed. We will need to reprogram the arduino nano to talk back to the RPI so that we can debug the issue.
